services:
  users-service:
    image: golang:1.22.1-alpine
    working_dir: /usr/src/app/users-service
    environment:
      AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./:/usr/src/app"
      - "$GOPATH/pkg/mod:/go/pkg/mod"

  notifications-service:
    image: golang:1.22.1-alpine
    working_dir: /usr/src/app/notifications-service
    environment:
      AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ENDPOINT_URL: http://localstack:4566
    volumes:
      - "./:/usr/src/app"
      - "$GOPATH/pkg/mod:/go/pkg/mod"

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: users
    volumes:
      - db-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  nats:
    image: docker.io/nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"

  debezium:
    platform: linux/amd64
    image: debezium/server:2.6
    volumes:
      - debezium-data:/debezium/data
      - ./debezium/application-nats.properties:/debezium/conf/application.properties
    environment:
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'
    depends_on:
      - db
      - nats

  nats-box:
    image: natsio/nats-box
    network_mode: "service:nats"

  localstack:
    image: localstack/localstack:3.4
    environment:
      - DEBUG=1
      - SERVICES=sqs
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:
  debezium-data:
  localstack-data:
