global:
  postgresql:
    postgresqlDatabase: mydatabase
    postgresqlUsername: myuser
    postgresqlPassword: mypassword

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
