apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
  NATS_URL: "nats://my-nats:4222"
  DB_DSN: host=postgres-postgresql user=myuser password=mypassword dbname=mydatabase port=5432 sslmode=disable TimeZone=Europe/Berlin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: main
        image: outbox-users-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: users-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
